"""
Pydantic schemas for request/response validation
"""
from .content import (
    ContentBlockBase,
    ContentBlockCreate,
    ContentBlockUpdate,
    ContentBlockResponse,
    TagBase,
    TagCreate,
    TagResponse,
    ContentVersionResponse,
)
from .proposal import (
    ProposalBase,
    ProposalCreate,
    ProposalUpdate,
    ProposalResponse,
    ProposalSectionBase,
    ProposalSectionCreate,
    ProposalSectionUpdate,
    ProposalSectionResponse,
    ProposalContentBase,
    ProposalContentCreate,
    ProposalContentUpdate,
    ProposalContentResponse,
    RFPRequirementBase,
    RFPRequirementCreate,
    RFPRequirementUpdate,
    RFPRequirementResponse,
)
from .common import PaginatedResponse

__all__ = [
    "ContentBlockBase",
    "ContentBlockCreate",
    "ContentBlockUpdate",
    "ContentBlockResponse",
    "TagBase",
    "TagCreate",
    "TagResponse",
    "ContentVersionResponse",
    "ProposalBase",
    "ProposalCreate",
    "ProposalUpdate",
    "ProposalResponse",
    "ProposalSectionBase",
    "ProposalSectionCreate",
    "ProposalSectionUpdate",
    "ProposalSectionResponse",
    "ProposalContentBase",
    "ProposalContentCreate",
    "ProposalContentUpdate",
    "ProposalContentResponse",
    "RFPRequirementBase",
    "RFPRequirementCreate",
    "RFPRequirementUpdate",
    "RFPRequirementResponse",
    "PaginatedResponse",
]
